from download_gtfs_sncf import main_download_gtfs
from download_osm_bordeaux import main_download_osm_graph
from filter_gtfs_bordeaux import main_download_filter_bordeaux
from download_train_station import main_download_trains
from generate_snapshot import generate_snapshot
main_download_gtfs()
main_download_osm_graph()
main_download_trains()
main_download_filter_bordeaux()
generate_snapshot()
