from download_gtfs_sncf import main_download_gtfs
from download_train_stations import main_download_trains
from download_parkings_stations import main_download_parkings
from download_osm_bordeaux import main_download_osm_graph
from extract_bordeaux_data import run_extraction
main_download_gtfs()
main_download_trains()
main_download_parkings()
run_extraction()
main_download_osm_graph()